../../bin/3way: 3way.c
	gcc 3way.c -g -I../../../sonLib/lib/ -I../../../pinchesAndCacti/externalTools/threeEdgeConnected/inc/ ../../../sonLib/lib/sonLib.a -lm ../../../sonLib/lib/3EdgeConnected.a -o 3way
	mv 3way ../../bin
